export const codingEnvironments = [
    {
      id: 'nodejs',
      name: 'Node.js',
      ignorePatterns: [
        'node_modules',
        'dist',
        'build',
        'logs',
        '*.log',
        '*.lock',
        '*.pid',
        '*.seed',
        '*.pid.lock',
        '*.swagger*',
        '*.wasm',
        'npm-debug.log*',
        'yarn-debug.log*',
        'yarn-error.log*',
        '.env*',
        '.editorconfig',
        '.eslintignore',
        '.eslintrc*',
        '.gitignore',
        '.prettierignore',
        '.prettierrc',
        '.stylelintrc',
        '.huskyrc',
        '.lintstagedrc',
        '.nvmrc',
        '.nycrc',
        '.tern-project',
        '.vscode',
        '.idea',
        '*.iml',
        '*.tsbuildinfo',
        '*.tgz',
        '.DS_Store',
        'Thumbs.db',
        'webpack.config*',
        'tsconfig*',
        'typedoc.json',
        'package-lock.json',
      ],
    },
    {
      id: 'react',
      name: 'React',
      ignorePatterns: [
        'node_modules',
        'build',
        'coverage',
        'dist',
        'logs',
        '*.log',
        '*.lock',
        '*.pid',
        '*.seed',
        '*.pid.lock',
        '*.tsbuildinfo',
        '.env*',
        '.eslintcache',
        '.stylelintcache',
        '.editorconfig',
        '.eslintignore',
        '.eslintrc*',
        '.gitignore',
        '.prettierignore',
        '.prettierrc',
        '.stylelintrc',
        '.huskyrc',
        '.lintstagedrc',
        '.nvmrc',
        '.nycrc',
        '.tern-project',
        '.vscode',
        '.idea',
        '*.iml',
        'webpack.config*',
        'tsconfig*',
      ],
    },
    {
      id: 'python',
      name: 'Python',
      ignorePatterns: [
        '__pycache__',
        'venv',
        '*.pyc',
        '*.pyo',
        '*.pyd',
        '*.so',
        '*.egg-info',
        'dist',
        'build',
        'logs',
        '*.log',
        '.env*',
        '.editorconfig',
        '.flake8',
        '.gitignore',
        '.pylintrc',
        '.pytest_cache',
        '.mypy_cache',
        '.rope',
        '.ropeproject',
        '.tox',
        '.coverage',
        '.hypothesis',
        '.python-version',
        '.scrapy',
        '*_venv',
      ],
    },
    {
      id: 'terraform',
      name: 'Terraform',
      ignorePatterns: [
        '.terraform',
        '*.tfstate',
        '*.tfstate.*',
        'crash.log',
        '*.tfvars',
        'override.tf',
        'override.tf.json',
        '*_override.tf',
        '*_override.tf.json',
        '.terraformrc',
        'terraform.rc',
        '.terraform.lock.hcl',
        '.DS_Store',
        'Thumbs.db',
      ],
    },
    {
      id: 'ansible',
      name: 'Ansible',
      ignorePatterns: [
        '*.retry',
        '*.log',
        '.gitignore',
        '.env*',
        'logs',
        '*.pid',
        '*.seed',
        '*.pid.lock',
        '.cache',
        '.editorconfig',
        '.vscode',
        '.idea',
        '*.iml',
        '*.swp',
        '*.swo',
        '.pylintrc',
        '.pytest_cache',
        '.mypy_cache',
      ],
    },
    {
      id: 'docker',
      name: 'Docker',
      ignorePatterns: [
        '*.pid',
        '*.seed',
        '*.pid.lock',
        'node_modules',
        'logs',
        '*.log',
        'coverage',
        '.env*',
        '.editorconfig',
        '.dockerignore',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'Dockerfile*',
        'docker-compose*.yml',
      ],
    },
    {
      id: 'kubernetes',
      name: 'Kubernetes',
      ignorePatterns: [
        '*.pid',
        '*.seed',
        '*.pid.lock',
        'logs',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'kubeconfig',
        '*.yaml',
        '*.yml',
        '*.json',
      ],
    },
    {
      id: 'golang',
      name: 'Go',
      ignorePatterns: [
        'bin',
        'pkg',
        'vendor',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.out',
        '*.test',
      ],
    },
    {
      id: 'java',
      name: 'Java',
      ignorePatterns: [
        'target',
        '*.class',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.jar',
        '*.war',
        '*.ear',
        '*.project',
        '*.classpath',
      ],
    },
    {
      id: 'dotnet',
      name: '.NET',
      ignorePatterns: [
        'bin',
        'obj',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.csproj.user',
        '*.suo',
        '*.user',
        '*.sln.docstates',
      ],
    },
    {
      id: 'ruby',
      name: 'Ruby',
      ignorePatterns: [
        '.bundle',
        'vendor/bundle',
        'log',
        'tmp',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.gem',
        'coverage',
        'spec/reports',
        '.rspec',
        '.rubocop.yml',
        '.simplecov',
      ],
    },
    {
      id: 'php',
      name: 'PHP',
      ignorePatterns: [
        'vendor',
        'logs',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'composer.lock',
        'composer.phar',
        'coverage',
        'phpunit.xml',
        'phpcs.xml',
        '.php_cs.cache',
      ],
    },
    {
      id: 'rust',
      name: 'Rust',
      ignorePatterns: [
        'target',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'Cargo.lock',
        'target/debug',
        'target/release',
        '*.rlib',
        '.rustup',
        '.cargo',
      ],
    },
    {
      id: 'swift',
      name: 'Swift',
      ignorePatterns: [
        'build',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.xcworkspace',
        '*.xcuserstate',
        '*.xcodeproj',
        'Pods',
        'DerivedData',
        '*.swiftpm',
        '*.swiftdeps',
        'Package.resolved',
      ],
    },
    {
      id: 'csharp',
      name: 'C#',
      ignorePatterns: [
        'bin',
        'obj',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '*.csproj.user',
        '*.suo',
        '*.user',
        '*.sln.docstates',
        'packages',
        'TestResults',
        '*.vs',
        '.nuget',
      ],
    },
    {
      id: 'perl',
      name: 'Perl',
      ignorePatterns: [
        'blib',
        'Build',
        '_build',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'local',
        'cover_db',
        'nyc_output',
        '.nycrc',
        '.nyc_output',
      ],
    },
    {
      id: 'elixir',
      name: 'Elixir',
      ignorePatterns: [
        '_build',
        'deps',
        'logs',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'cover',
        '.elixir_ls',
        'test-coverage',
        'mix.lock',
      ],
    },
    {
      id: 'haskell',
      name: 'Haskell',
      ignorePatterns: [
        'dist-newstyle',
        'cabal.sandbox.config',
        'cabal.project.local',
        'cabal.project.local~',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'dist',
        'dist-*',
        '.stack-work',
      ],
    },
    {
      id: 'scala',
      name: 'Scala',
      ignorePatterns: [
        'target',
        'project/target',
        'project/.history',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        '.bloop',
        '.metals',
        '.ammonite',
        '.ensime_cache',
        '.ensime',
      ],
    },
    {
      id: 'dart',
      name: 'Dart',
      ignorePatterns: [
        '.dart_tool',
        'build',
        '*.log',
        '.env*',
        '.editorconfig',
        '.gitignore',
        '.vscode',
        '.idea',
        '*.iml',
        'packages',
        '.packages',
        'pubspec.lock',
        'coverage',
        '.flutter-plugins',
        '.flutter-plugins-dependencies',
      ],
    },
  ];